steps:
  # temporary, for testing
  - id: clone
    name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args:
      - -c
      - |
        git clone -b ${_BUTTON_BRANCH} https://github.com/${_BUTTON_REPO}/cloud-run-button ${_WORKING_DIR}

  - id: build
    name: golang:${_VERSION}
    entrypoint: /bin/bash
    dir: ${_WORKING_DIR}
    env:
      - "GOPATH=/workspace"
    args:
      - -c
      - |
        go build -o /workspace/cloudshell_open ./cmd/cloudshell_open

  - name: "google/cloud-sdk"
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  - id: run tests
    name: "google/cloud-sdk"
    env:
      - "GOOGLE_CLOUD_PROJECT=$PROJECT_ID"
      - "GOOGLE_CLOUD_REGION=${_REGION}"
      - "GIT_URL=https://github.com/glasnt/crb-appjson-test"
      - "GIT_BRANCH=integration_tests"
      - "PYTHONUNBUFFERED=true"
    script: |
      #!/bin/bash -e
      python3 run_integration_test.py --description "no config" --directory empty-appjson --expected_text 'hello, world'
      python3 run_integration_test.py --description "inline hooks" --directory hooks-prepostcreate-inline --expected_text 'AB'

      python3 run_integration_test.py --description "external hooks" --directory hooks-prepostcreate-external --expected_text '3'
      python3 run_integration_test.py --description "external hooks, dirty" --directory hooks-prepostcreate-external --expected_text '3' --dirty

      python3 run_integration_test.py --description "generator" --directory envvars-generated
      GEN_URL=$(gcloud run services describe  envvars-generated --region $GOOGLE_CLOUD_REGION --format "value(status.url)")
      OUTPUT=$(curl $GEN_URL --silent)
      python3 run_integration_test.py --description "generator, dirty" --directory envvars-generated --dirty --expected_text $OUTPUT

      python3 run_integration_test.py --description "options test - memory/cpu" --directory memory-cpu --expected_text 'hello, world'

      python3 run_integration_test.py --description "options test - other configs" --directory options --expected_text 'hello, world'

substitutions:
  _VERSION: "1.18"
  _WORKING_DIR: /workspace/cloud-run-button
  _REGION: us-central1
  _BUTTON_BRANCH: master
  _BUTTON_REPO: googlecloudplatform
