steps:
  # temporary, for testing
  - id: clone
    name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args:
      - -c
      - |
        git clone -b ${_BUTTON_BRANCH} https://github.com/${_BUTTON_REPO}/cloud-run-button ${_WORKING_DIR}

  - id: build
    name: golang:${_VERSION}
    entrypoint: /bin/bash
    dir: ${_WORKING_DIR}
    env:
      - "GOPATH=/workspace"
    args:
      - -c
      - |
        go build -o /workspace/cloudshell_open ./cmd/cloudshell_open

  - name: "google/cloud-sdk"
    entrypoint: pip
    args: ['install', '-r', 'requirements.txt', '--user']


#  - id: empty-appjson
#    name: "google/cloud-sdk"
#    entrypoint: python3
#    env:
#      - "GOOGLE_CLOUD_PROJECT=$PROJECT_ID"
#      - "GOOGLE_CLOUD_REGION=${_REGION}"
#      - "GIT_URL=https://github.com/glasnt/crb-appjson-test"
#      - "GIT_BRANCH=integration_tests"
#    args: ["run_integration_test.py", "--directory", "empty-appjson", "--expected_text", 'hello, world']

  - id: run tests
    name: "google/cloud-sdk"
    env:
      - "GOOGLE_CLOUD_PROJECT=$PROJECT_ID"
      - "GOOGLE_CLOUD_REGION=${_REGION}"
      - "GIT_URL=https://github.com/glasnt/crb-appjson-test"
      - "GIT_BRANCH=integration_tests"
    script: | 
      #!/bin/bash
      python3 run_integration_test.py --directory empty-appjson --expected_text 'hello, world'
      python3 run_integration_test.py --directory hooks-prepostcreate-inline --expected_text 'AB'

      python3 run_integration_test.py --directory hooks-prepostcreate-external --expected_text '3'
      python3 run_integration_test.py --directory hooks-prepostcreate-external --expected_text '3' --clean

      OUTPUT=python3 run_integration_test.py --directory envvars-generated
      python3 run_integration_test.py --directory envvars-generated --clean --expected_text '$$OUTPUT'

      python3 run_integration_test.py --directory memory-cpu --expected_text 'hello, world'

      python3 run_integration_test.py --directory options --expected_text 'hello, world'


substitutions:
  _VERSION: "1.18"
  _WORKING_DIR: /workspace/cloud-run-button
  _REGION: us-central1
  _BUTTON_BRANCH: master
  _BUTTON_REPO: googlecloudplatform
